### ISSUE TITLE
安装完后，用设定的管理员账号登陆不了

### ISSUE THREAD

**Issue by taomujian** [midoks/imail#27]
2022/06/08 17:15:43 /Users/midoks/go/src/github.com/midoks/imail/internal/db/domain.go:119 record not found
[0.119ms] [rows:0] SELECT * FROM `im_domain` WHERE a=1 AND mx=1 AND spf=1 AND dkim=1 AND dmarc=1 AND is_default=1 ORDER BY `im_domain`.`id` LIMIT 1

报这个错误

**Comment by midoks** [comment]
你查看一下数据库，是否存在用户的数据。

**Comment by midoks** [comment]
我本地测试了，mysql,sqlite3都没有问题。你可以删除custom文件，如果是mysql，清空数据，sqlite，删除data/imail.db3文件，重现安装一下。

**Comment by taomujian** [comment]
![image](https://user-images.githubusercontent.com/47107775/172752960-b1cdcf09-dbd9-4b98-9488-a5372eff47f5.png)

前端报这个错误

**Comment by midoks** [comment]
你可以把你的信息，通过邮件发送给我，我没有遇到这种清空，需要在线调试。

**Comment by taomujian** [comment]
你邮箱是什么呢？

**Comment by midoks** [comment]
midoks@163.com

**Comment by taomujian** [comment]
好的，收到，上条留言可以删了

**Comment by midoks** [comment]
初始化配置文件cookie_secure = true 为http严格模式，改为false。
