### ISSUE TITLE
默认安装时缺少 SQLite3 文件

### ISSUE THREAD

**Issue by skiy** [midoks/imail#5]
执行安装脚本完成后，启动不成功。没有 `./data/imail.db3` 这个文件。

![image](https://user-images.githubusercontent.com/3362147/134768351-3619654c-720f-4d70-a744-2b24f793588a.png)

**Comment by midoks** [comment]
你什么系统？


> 执行安装脚本完成后，启动不成功。没有 `./data/imail.db3` 这个文件。
> 
> ![image](https://user-images.githubusercontent.com/3362147/134768351-3619654c-720f-4d70-a744-2b24f793588a.png)

1.你什么系统。二进制都错了！
2.你尝试用源码编译运行一下，看看什么问题，解决后，给我说说

**Comment by skiy** [comment]
1. CentOS 8.4
2. 那个错误是启动时报的错误，panic 时就是这样报错的。对应文件的 32 行正好是打开 `sqlite3` 文件。
![image](https://user-images.githubusercontent.com/3362147/134768906-90618410-3827-47fe-8db7-c85ca2092c02.png)

**Comment by midoks** [comment]
> 1. CentOS 8.4
> 2. 那个错误是启动时报的错误，panic 时就是这样报错的。对应文件的 32 行正好是打开 `sqlite3` 文件。
>    ![image](https://user-images.githubusercontent.com/3362147/134768906-90618410-3827-47fe-8db7-c85ca2092c02.png)
> 
> **重新编译可以执行了。**

1. 你试试设置 CGO_ENABLED=1，不行的话
2. 源码编译下[你shell写的好,顺便优化一下，😊]:
curl -fsSL  https://raw.githubusercontent.com/midoks/imail/master/scripts/install_dev.sh | sh

**Comment by skiy** [comment]
在 `release` 下载的包执行不了：
![image](https://user-images.githubusercontent.com/3362147/134769205-9bc0dda3-68dc-4570-95ab-1a45ed7c400d.png)

另外，刚才的我试过修改参数也不行。

**Comment by midoks** [comment]
> 在 `release` 下载的包执行不了：
> ![image](https://user-images.githubusercontent.com/3362147/134769205-9bc0dda3-68dc-4570-95ab-1a45ed7c400d.png)
> 
> 另外，刚才的我试过修改参数也不行。

说明我release文件有问题，我查查，看这么解决这个编译问题。

**Comment by skiy** [comment]
可以尝试下用 `GitHub Action` CI/CD 自动 BUILD。我看到有人用它自动 Build 过。
- https://github.com/winterssy/mxget/blob/master/.github/workflows/build.yml

另外，可以尝试一下用这个工具。我之前用过，还不错：
- https://github.com/goreleaser/goreleaser

**Comment by midoks** [comment]
> * https://github.com/winterssy/mxget/blob/master/.github/workflows/build.yml

不是这个哟。我在本地打包，好上传呀。
https://github.com/midoks/imail/blob/master/scripts/pick.sh

**Comment by skiy** [comment]
> > * https://github.com/winterssy/mxget/blob/master/.github/workflows/build.yml
> 
> 不是这个哟。我在本地打包，好上传呀。
> https://github.com/midoks/imail/blob/master/scripts/pick.sh

看了下 `go-sqlite3` 的环境要求，编译的时候需要将 `CGO_ENABLED=1`。
```bash
Important: because this is a CGO enabled package you are required to set the environment variable CGO_ENABLED=1 and have a gcc compile present within your path.
```
- https://github.com/mattn/go-sqlite3/blob/master/README.md

你这个 pick.sh 文件将它设置成 0 了。
- https://github.com/midoks/imail/blob/master/scripts/pick.sh#L18

**Comment by midoks** [comment]
> > > * https://github.com/winterssy/mxget/blob/master/.github/workflows/build.yml
> > 
> > 
> > 不是这个哟。我在本地打包，好上传呀。
> > https://github.com/midoks/imail/blob/master/scripts/pick.sh
> 
> 看了下 `go-sqlite3` 的环境要求，编译的时候需要将 `CGO_ENABLED=1`。
> 
> ```shell
> Important: because this is a CGO enabled package you are required to set the environment variable CGO_ENABLED=1 and have a gcc compile present within your path.
> ```
> 
> * https://github.com/mattn/go-sqlite3/blob/master/README.md
> 
> 你这个 pick.sh 文件将它设置成 0 了。
> 
> * https://github.com/midoks/imail/blob/master/scripts/pick.sh#L18

我试了一下，体积增加一倍，我本地和测试都运行不了。😅。
```
[root@izt4n99ftdj3ucsc22b7cyz imail]# ./imail -v
-bash: ./imail: cannot execute binary file
```

**Comment by skiy** [comment]
可以跑个 `Docker` 来测试。
体积的话，我在服务器上跑的，直接 build 有 `22M`；加参数的话 `15M`。
```
# go build -ldflags="-s -w" 
-rwxr-xr-x   1 root root  15M Sep 25 19:43 imail

# go build
-rwxr-xr-x   1 root root  22M Sep 25 18:56 imail1
```

**Comment by midoks** [comment]
> 可以跑个 `Docker` 来测试。
> 体积的话，我在服务器上跑的，直接 build 有 `22M`；加参数的话 `15M`。
> 
> ```
> # go build -ldflags="-s -w" 
> -rwxr-xr-x   1 root root  15M Sep 25 19:43 imail
> 
> # go build
> -rwxr-xr-x   1 root root  22M Sep 25 18:56 imail1
> ```

体积是次要原因，主要是不能运行。

**Comment by midoks** [comment]
1. goreleaser 方案  -> 并不支持交叉编译 | 但是可以通过docker来解决 {未尝试}，我的破电脑带不起了。
2. 本机方案
```
brew install FiloSottile/musl-cross/musl-cross -> linux
brew install mingw-w64   -> windows
``` 

linux/amd64打包没有问题，但是其他架构就不行了。

```
brew install FiloSottile/musl-cross/musl-cross --with-i486 --with-x86_64 --with-aarch64 --with-arm
```

linux/amd64和linux/386，linux/arm64， linux/arm不能同时存在。

以后打包暂时只有linux/amd64，darwin/amd64， windows/386，windows/amd64。

交叉编译太费劲了。

https://github.com/midoks/imail/blob/master/scripts/pick.sh#L60
