### ISSUE TITLE
mail前端页面

### ISSUE THREAD

**Issue by xmapst** [midoks/imail#6]
邮箱前端可以将就使用这个先[alps](https://github.com/xmapst/alps)

**Comment by midoks** [comment]
我搞半天，硬是不知道如何启动呀。

```
midoks@midoks alps % go run ./cmd/alps imap://127.0.0.1:143 smtp://127.0.0.1:25 
signal: interrupt
midoks@midoks alps % go run ./cmd/alps imap://127.0.0.1:993 smtp://127.0.0.1:465
2021-09-29T01:13:39+08:00 FATAL failed to connect to IMAP server: failed to connect to IMAP server: dial tcp 127.0.0.1:993: connect: connection refused
exit status 1
midoks@midoks alps % go run ./cmd/alps example.org                                
2021-09-29T01:15:13+08:00 FATAL failed to discover IMAP server: IMAP service discovery not configured for domain "example.org"
exit status 1
midoks@midoks alps % go run ./cmd/alps cachecha.com
2021-09-29T01:15:32+08:00 FATAL failed to discover IMAP server: IMAP service discovery not configured for domain "cachecha.com"
exit status 1
midoks@midoks alps % 
midoks@midoks alps % go run ./cmd/alps mail.cachecha.com
2021-09-29T01:19:53+08:00 FATAL failed to discover IMAP server: IMAP service discovery not configured for domain "mail.cachecha.com"
exit status 1
```

**Comment by xmapst** [comment]
> 我搞半天，硬是不知道如何启动呀。
> 
> ```
> midoks@midoks alps % go run ./cmd/alps imap://127.0.0.1:143 smtp://127.0.0.1:25 
> signal: interrupt
> midoks@midoks alps % go run ./cmd/alps imap://127.0.0.1:993 smtp://127.0.0.1:465
> 2021-09-29T01:13:39+08:00 FATAL failed to connect to IMAP server: failed to connect to IMAP server: dial tcp 127.0.0.1:993: connect: connection refused
> exit status 1
> midoks@midoks alps % go run ./cmd/alps example.org                                
> 2021-09-29T01:15:13+08:00 FATAL failed to discover IMAP server: IMAP service discovery not configured for domain "example.org"
> exit status 1
> midoks@midoks alps % go run ./cmd/alps cachecha.com
> 2021-09-29T01:15:32+08:00 FATAL failed to discover IMAP server: IMAP service discovery not configured for domain "cachecha.com"
> exit status 1
> midoks@midoks alps % 
> midoks@midoks alps % go run ./cmd/alps mail.cachecha.com
> 2021-09-29T01:19:53+08:00 FATAL failed to discover IMAP server: IMAP service discovery not configured for domain "mail.cachecha.com"
> exit status 1
> ```

好吧, 可能不适配
