### ISSUE TITLE
A记录无法识别

### ISSUE THREAD

**Issue by X7A600** [midoks/imail#62]
已经添加了MX.example.domain和example.domain A记录到服务器IP
我使用的是
curl -fsSL  https://raw.githubusercontent.com/midoks/imail/master/scripts/install.sh | sh
我的系统为CentOS Linux release 7.9.2009
[![xW](https://s1.ax1x.com/2022/10/26/xWxMRS.png)]
[![xWxBM4.png](https://s1.ax1x.com/2022/10/26/xWxBM4.png)]

**Comment by X7A600** [comment]
> example.domain

**Comment by sunyue1380** [comment]
不好意思挖个坟，我也遇到同样的问题，dns已经按照要求配置了，也是显示A记录无法识别，其他的都已经打勾了。
